Added my profile :zap:
wzhouwzhou/one-line-wonders pull request #333
Opened 2019-10-01 13:39 UTC by Yusadolat

**Please describe your program and how to run it.**

...something... (replace this line)

--------
**What Programming Language?**

...language...

2019-10-01 18:48 UTC, wzhouwzhou commented on CONTRIBUTORS.md
> -﻿Name: [Hugo Nunes](https://github.com/hugonun)<br/>
What happened in this line?

2019-10-02 09:52 UTC, Yusadolat commented on CONTRIBUTORS.md
> -﻿Name: [Hugo Nunes](https://github.com/hugonun)<br/>
I dunno, Is something wrong?

2019-10-02 15:37 UTC, kannagikazuko commented on CONTRIBUTORS.md
> -﻿Name: [Hugo Nunes](https://github.com/hugonun)<br/>
To guard against merge conflicts, would you mind pushing a revert commit on this hunk? I do not know what changed in this line that the diff is highlighting.

2019-10-02 18:06 UTC, wzhouwzhou requested changes
(Please see above request, in the future, it'd be best to just submit code additions)

2019-10-03 09:14 UTC, closed without merging