Fix empty output in bash/ip.sh.
wzhouwzhou/one-line-wonders pull request #334
Opened 2019-10-01 13:43 UTC by icedream

This pull request is merely a quick fix for the Bash IP read-out script, replacing the `cut` call with `awk`. This allows the script to be more tolerant with indenting spaces.

2019-10-01 13:54 UTC, wzhouwzhou commented
I am unable to reach the original author of the file, Mohammed Nisham; out of respect, would you mind renaming this as a new file, such as `icedream_ip.sh`?

2019-10-02 18:08 UTC, wzhouwzhou requested changes
(Please see above request about renaming to icedream_ip.sh)

2019-10-02 20:40 UTC, icedream commented
Can't find a way to respond to your review anymore but I have done the requested changes now. :)

2019-10-02 23:48 UTC, wzhouwzhou submitted a review, later dismissed

2019-10-17 18:35 UTC, kannagikazuko submitted a review, later dismissed

2019-10-17 18:37 UTC, kannagikazuko approved these changes

2019-10-17 18:39 UTC, merged