Included factorial program in C language
wzhouwzhou/one-line-wonders pull request #351
Opened 2019-10-03 10:55 UTC by YenruoY

**Please describe your program and how to run it.**
Factorial program that takes a number as a command line argument and prints the factorial 

--------
**What Programming Language?**

Language Used : C
Compiler used : GCC

2019-10-03 13:27 UTC, wzhouwzhou requested changes

2019-10-03 13:27 UTC, wzhouwzhou commented on CONTRIBUTORS.md
> +Email: benjamin@ericsart.com</br>
To avoid merge conflicts, would you mind reversing these changes?

2019-10-04 09:56 UTC, YenruoY reviewed
I think its done

2019-10-04 13:11 UTC, wzhouwzhou approved these changes
Looks good now, thanks!

2019-10-11 18:57 UTC, closed without merging

2019-10-11 19:05 UTC, wzhouwzhou commented
Why was this closed?