Add a really short javascript fizzbuzz example
wzhouwzhou/one-line-wonders pull request #364
Opened 2019-10-04 19:29 UTC by Unaidedsteak

**Please describe your program and how to run it.**

A "Code Golfed" example of Fizz Buzz

--------
**What Programming Language?**

Javascript

2019-10-05 04:41 UTC, wzhouwzhou commented
Wow a console.log in the 3rd for block, something different than what I'm used to and still "hacky", I like it! I would've thought to use a (log || operation) since console.log always returns void 0.

2019-10-05 04:41 UTC, wzhouwzhou approved these changes

2019-10-30 20:53 UTC, kannagikazuko commented
Please give us access or resolve conflicts and follow the naming convention, thanks!

2019-10-30 20:53 UTC, kannagikazuko requested changes
File format

2019-11-11 16:01 UTC, closed without merging