Added program that checks if the number is a square number
wzhouwzhou/one-line-wonders pull request #369
Opened 2019-10-06 09:50 UTC by U3X

**Please describe your program and how to run it.**

Program asks for a number, and prints whether it is a square number or not.

--------
**What Programming Language?**

C++

2019-10-07 00:09 UTC, wzhouwzhou submitted a review, later dismissed

2019-10-07 00:09 UTC, wzhouwzhou commented on cplusplus/check_square.cpp
> +int flag=1;	for(long long  i=1;i<=a/2+1;i++){	if(i*i==a)	{cout<<"it is a square number\n";flag=0;}	}if(flag==1)	cout<<"Not a square number\n";
flag isn't modified and this whole if statement for cout can be simplified down to one line via ```c
cout << condition ? <const char*>1 : <const char*>2```

2019-10-17 19:15 UTC, kannagikazuko requested changes
Bump

2019-10-26 18:33 UTC, wzhouwzhou commented
Due to lack of activity, we'll be moving this to the honorary folder.

2019-10-30 20:48 UTC, kannagikazuko approved these changes

2019-10-30 20:49 UTC, merged